FROM alpine:3.16
ARG BUILD_VER
ARG TIMEZONE
WORKDIR /home/foundry/vtt
COPY ./${BUILD_VER}/ .
RUN set -xe \
    && export \
    && apk add --no-cache --update shadow nodejs icu-data-full npm tzdata \
    && addgroup -g 3000 -S foundry \
    && adduser -g 3000 -S foundry -G foundry \
    && usermod -u 3000 foundry \
    && npm install -g uuid@latest \
    && npm install -g pm2 \
    && apk del --no-cache npm shadow \
    && mkdir -p /home/foundry/userdata \
    && sed -i 's/Update Software/Update Disabled/' /home/foundry/vtt/resources/app/public/lang/en.json \
    && sed -i 's/"You may update your Foundry Virtual Tabletop software to a new version by checking for update on your preferred Software Update Channel."/"In app updates are disabled, please use VTTctl for updates and upgrades instead."/' /home/foundry/vtt/resources/app/public/lang/en.json \
    && sed -i 's/"Check For Update"/"In app updates are disabled, please use VTTctl for updates and upgrades instead."/' /home/foundry/vtt/resources/app/public/lang/en.json \    
    && sed -i 's/{{#unless updateButtonEnabled}}disabled{{\/unless}}/disabled/' /home/foundry/vtt/resources/app/templates/setup/setup-config.html \       
    && chown foundry:foundry -R /home/foundry/ \
    && chmod +x /home/foundry/vtt/docker-entrypoint.sh \
    && touch /home/foundry/.firstboot


ENV TZ=${TIMEZONE}
USER foundry
EXPOSE 30000
ENTRYPOINT [ "/home/foundry/vtt/docker-entrypoint.sh" ]