#!/usr/bin/env bash
ENV_FILE=.env
if [ -f ${ENV_FILE} ]; then
  export $(cat .env | xargs)
fi

NAME=${VTT_NAME}
DESC=Environment
PROD_PROJECT="${NAME}_PROD"
DEV_PROJECT="${NAME}_DEV"
REGEX_URL='(https?|ftp|file)://[-[:alnum:]\+&@#/%?=~_|!:,.;]*[-[:alnum:]\+&@#/%=~_|]'

# Source function library.
if ! [ -x "/lib/lsb/init-functions" ]; then
        . /lib/lsb/init-functions
else
        echo "E: /lib/lsb/init-functions not found, lsb-base (>= 3.0-6) needed"
        exit 1
fi

if [ -f scripts/functions ]; then
        . ./scripts/functions
fi

IN_DOCKER=$(id -nG "$USER" | grep -qw "docker")

if [[ "root" != ${USER} ]] && [[ $IN_DOCKER ]]; then
    log_failure_msg "Usage: sudo $0 \n - alternative: add $USER to docker group."
    exit 1
fi 

case "$1" in
  start)
        log_daemon_msg "Starting $DESC" "$NAME"
        docker-compose -p $PROD_PROJECT -f docker/docker-compose.yml up -d
        docker-compose -p $DEV_PROJECT -f docker/docker-compose-dev.yml up -d
        log_end_msg $?
        ;;
  stop)
        log_daemon_msg "Stopping $DESC" "$NAME"
        stop
        log_end_msg $?
        ;;
  logs)
        getLogs
        ;;
  clean)
        $0 stop
        docker-compose -p $PROD_PROJECT -f docker/docker-compose.yml down
        docker-compose -p $DEV_PROJECT -f docker/docker-compose-dev.yml down
        docker rmi foundryvtt:latest
        ;;
  build)
        log_daemon_msg "Building $DESC" "$NAME"
        cp FoundryVTT/docker-entrypoint.sh FoundryVTT/vtt/
        docker build -t foundryvtt:latest -f ./FoundryVTT/Dockerfile ./FoundryVTT
        log_end_msg $?
        ;;
  rebuild)
        $0 clean
        $0 build
        log_end_msg $?
        ;;   
  reload|force-reload)
        log_daemon_msg "Reloading $DESC configuration files for" "$NAME"
        appReload
        log_end_msg $?
        ;;
  status)
         json=$(getVersion)
         if [[ ! -z "$json" ]]; then
                if jq -e . >/dev/null 2>&1 <<<"$json"; then
                        IS_ACTIVE=$(echo $json | jq .active)
                        VERSION=$(echo $json | jq -r .version)
                        if [ $IS_ACTIVE = "true" ]; then
                                WORLD=$(echo $json | jq -r .world)
                                SYSTEM=$(echo $json | jq -r .system)
                                log_daemon_msg "Foundry VTT v$VERSION is running."
                                log_daemon_msg " System: ${SYSTEM}"
                                log_daemon_msg " World: ${WORLD//-/ }"
                                true
                                log_end_msg $?
                        else
                                log_daemon_msg "Foundry VTT v$VERSION is running BUT world not active."
                                true
                                log_end_msg $?   
                        fi
                else
                        false
                        log_daemon_msg "Foundry VTT is not running."
                        log_end_msg $?
                fi
         else
                log_daemon_msg "Foundry VTT is not running."
                log_end_msg $?      
         fi
         ;;
  restart)
        $0 stop
        sleep 1
        $0 start
        ;;
  backup)
        log_daemon_msg "Backing up Foundry VTT."
        prodBackup
        log_end_msg $?      
        ;;
  restore)
        log_daemon_msg "Restoring up Foundry VTT."
        prodLatestRestore
        $0 reload
        log_end_msg $?      
        ;;
  restoredev)
        log_daemon_msg "Restoring up Foundry VTT."
        devLatestRestore
        $0 reload
        log_end_msg $?      
        ;;        
  download)
        if [[ $2 =~ $REGEX_URL ]]; then 
            U_EXPIRES=$(echo $2 | awk -F= '{print $4}')
            U_NOW=$(date '+%s')
            if [[ U_NOW -gt U_EXPIRES ]]; then
                echo "Foundry VTT Timed URL expired."
                false
                log_end_msg $? 
            else
                FILE=$(basename $(echo $2 | awk -F\? '{ print $1 }'))
                echo $FILE
                log_daemon_msg "Downloading Foundry VTT version v$VERSION"
                true
                log_end_msg $?      
            fi
        else
            echo "Usage: $0 download \"Foundry VTT Linux/NodeJS download timed URL\""
        fi
        ;;   
  *)
        log_failure_msg "Usage: $N {start|stop|logs|clean|build|rebuild|status|restart|reload|force-reload}"
        exit 1
        ;;
esac






