version: '3.9'

services:
    ddb:
      restart: unless-stopped
      image: ghcr.io/mrprimate/ddb-proxy:latest
      environment:
          - PORT=3000
      ports:
        - "3000:3000/tcp"
      networks:
       - internal_A
    app:
      user: 3000:3000
      restart: always
      image: foundryvtt:${TAG:-latest}
      volumes:
       - UserData:/home/foundry/userdata
       - shared_jb2a_patreon:/home/foundry/userdata/Data/modules/jb2a_patreon
       - shared_ivan-duch-music-packs:/home/foundry/userdata/Data/modules/ivan-duch-music-packs/
       - shared_tabletop-rpg-music:/home/foundry/userdata/Data/modules/tabletop-rpg-music/
       - shared_michaelghelfi:/home/foundry/userdata/Data/modules/michaelghelfi/
       - ../backups/FoundryVTT:/home/foundry/vtt/resources/app/public/backups/:ro
      networks:
       - internal_A
    web:
      image: nginx:alpine
      restart: always
      volumes:
        - ./nginx/foundry.conf:/etc/nginx/templates/default.conf.template:ro
        - ../backups/FoundryVTT:/var/www/backups/:ro
      ports:
        - "${NGINX_PROD_PORT}:80/tcp"
      networks:
       - internal_A

volumes:
    UserData:
    shared_jb2a_patreon:
        name: shared_jb2a_patreon
    shared_ivan-duch-music-packs:
        name: shared_ivan-duch-music-packs
    shared_tabletop-rpg-music:
        name: shared_tabletop-rpg-music
    shared_michaelghelfi:
        name: shared_michaelghelfi

networks:
    internal_A:
