version: '3.9'

services:
    ddb:
      restart: unless-stopped
      image: ghcr.io/mrprimate/ddb-proxy:latest
      environment:
          - PORT=3000
      ports:
        - "3000:3000/tcp"
    app:
      user: 3000:3000
      restart: always
      environment:
       - VARS=${VARS}
      image: foundryvtt:${TAG:-latest}
      networks:
        - backend
      volumes:
       - UserData:/home/foundry/userdata
       - ../backups/FoundryVTT/native:/home/foundry/userdata/Backups
    web:
      image: nginx:alpine
      restart: always
      volumes:
        - ./nginx/foundry.conf:/etc/nginx/templates/default.conf.template:ro
        - ../backups/FoundryVTT:/var/www/backups/:ro
        - ./nginx/critical_fail.html:/var/www/critical_fail.html:ro
      ports:
        - "${NGINX_PROD_PORT}:80/tcp"
      networks:
        - frontend
        - backend
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=frontend"
        - "traefik.http.routers.vtt.entrypoints=web"
        - "traefik.http.routers.vtt.rule=Host(`vtt.legendaryrealms.com.mx`)"

volumes:
    UserData:

networks:
  frontend:
    external: true
  backend: