version: '3.9'

services:
    ddb:
      restart: unless-stopped
      image: ghcr.io/mrprimate/ddb-proxy:latest
      environment:
          - PORT=3000
      ports:
        - "3000:3000/tcp"
      networks:
       - internal_A
    app:
      restart: unless-stopped
      image: foundryvtt:${TAG:-latest}
      volumes:
       - UserData:/home/foundry/userdata
      networks:
       - internal_A
    web:
      image: nginx:alpine
      restart: unless-stopped
      volumes:
        - ./nginx/foundry.conf:/etc/nginx/templates/default.conf.template:ro
      ports:
        - "${NGINX_PROD_PORT}:80/tcp"
      networks:
       - internal_A

volumes:
    UserData:

networks:
    internal_A:
